### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by The-Radiant-Sun** [nick17773/ProgrammingAssesment2.7#2]
textCipherVer1.exe:
Looping issue - Should not ask whether to use the function the first running
Information issue - Should provide information regarding the cypher
Information issue - 'Shift Offset' is a good way to confuse ignorant people when no information is provided
Information issue - No information regarding history
ver1.exe:
Visual issue - Reorganize GUI to be more space efficiant
Information issue - Should provide information
Crash - Crashes when no key inputted
Information issue - Histories should be combined
Information issue - Histories should provide history, call it 'previous input' or something similar if it is not history
Information issue - CSV information should be provided
Redundancy - End button is redundant, there is the window close button to do it as well

**Comment by nick17773** [comment]
reviewed
